name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Splash
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4


  google_sign_in: ^6.0.0
  
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0


  connectivity_plus: ^6.1.2
  internet_connection_checker_plus: ^2.5.2


  provider: ^6.1.2
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.9.0


  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

  adaptive_icon_foreground: "assets/icons/app_icon.png"
  adaptive_icon_background: "#ef9629"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
    - assets/images/splash.png
    - assets/images/user_icon.png
    - assets/categories/herbs.png
    - assets/categories/spices.png
    - assets/categories/oils.png
    - assets/categories/honey.png
    - assets/categories/cosmetics.png
    - assets/categories/bundles.png
    - assets/categories/best_sellers.png