name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

  firebase_core: ^3.0.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
  generate: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"

  image: assets/images/logo.png
  image_dark: assets/images/logo.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    image: assets/images/logo.png
    image_dark: assets/images/logo.png
    
  android: true
  ios: true
  web: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  min_sdk_android: 21